/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EditClient: typeof import('./src/components/admin/EditClient.vue')['default']
    EditFactory: typeof import('./src/components/admin/EditFactory.vue')['default']
    EditIdentity: typeof import('./src/components/admin/EditIdentity.vue')['default']
    EditMedicine: typeof import('./src/components/admin/EditMedicine.vue')['default']
    EditOperator: typeof import('./src/components/admin/EditOperator.vue')['default']
    EditOrderDetail: typeof import('./src/components/admin/EditOrderDetail.vue')['default']
    EditOrderRecord: typeof import('./src/components/admin/EditOrderRecord.vue')['default']
    EditStore: typeof import('./src/components/admin/EditStore.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HomePage: typeof import('./src/components/admin/HomePage.vue')['default']
    InsertClient: typeof import('./src/components/admin/InsertClient.vue')['default']
    LikeMessage: typeof import('./src/components/admin/LikeMessage.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    ManageClient: typeof import('./src/components/admin/ManageClient.vue')['default']
    ManageFactory: typeof import('./src/components/admin/ManageFactory.vue')['default']
    ManageIdentity: typeof import('./src/components/admin/ManageIdentity.vue')['default']
    ManageMedicine: typeof import('./src/components/admin/ManageMedicine.vue')['default']
    ManageOperator: typeof import('./src/components/admin/ManageOperator.vue')['default']
    ManageOrderDetail: typeof import('./src/components/admin/ManageOrderDetail.vue')['default']
    ManageOrderRecord: typeof import('./src/components/admin/ManageOrderRecord.vue')['default']
    ManageStore: typeof import('./src/components/admin/ManageStore.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
