server:
  port: 9421
  servlet:
    context-path: /tzb
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://127.0.0.1:3306/yaofang?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123123
#    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: tzb.pojo
#  mapper-locations: classpath:mappers/*.xml


